#############################################################################
# vsrx01 Configuration File
#
# Options:
# - hostname: the hostname of the VM
# - default_gw: Default gateway
#
# - interfaces list:
#   + interface: Junos interface name
#   + description: Interface description
#   + address: IP address of the interface
#   + mask: bit count of the network mask
#
# - security.zones dictionary:
#   + interface: Interface name
#   + name: Security zone name
#############################################################################
host_name: vsrx01
default_gw: 10.0.0.2
interfaces:
    - interface: ge-0/0/1
      description: to_vsrx02
      address: 10.0.0.1
      mask: 24
    - interface: ge-0/0/2
      description: to_vsrx03
      address: 192.168.1.1
      mask: 24
security:
    zones:
      - interface: ge-0/0/1
        name: untrust
      - interface: ge-0/0/2
        name: trust

